name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            3.1.x
            6.0.x
            7.0.x
            8.0.x
    
      - name: Restore
        run: dotnet restore IT.Utf8String.sln
    
      - name: Build
        run: dotnet build IT.Utf8String.sln --configuration Release --no-restore 
    
      - name: Test
        run: dotnet test IT.Utf8String.Tests/IT.Utf8String.Tests.csproj --configuration Release --no-restore

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish IT.Utf8String
        uses: pairbit/publish-nuget@v2.6.1
        with:
            PROJECT_FILE_PATH: IT.Utf8String/IT.Utf8String.csproj
            NUGET_KEY: ${{secrets.NUGET}}
            TAG_COMMIT: true

      - name: Publish IT.Utf8String.MemoryPack
        uses: pairbit/publish-nuget@v2.6.1
        with:
            PROJECT_FILE_PATH: IT.Utf8String.MemoryPack/IT.Utf8String.MemoryPack.csproj
            NUGET_KEY: ${{secrets.NUGET}}
            TAG_COMMIT: true
            
      - name: Publish IT.Utf8String.AspNetCore
        uses: pairbit/publish-nuget@v2.6.1
        with:
            PROJECT_FILE_PATH: IT.Utf8String.AspNetCore/IT.Utf8String.AspNetCore.csproj
            NUGET_KEY: ${{secrets.NUGET}}
            TAG_COMMIT: true
